services:
  # Web Service (Django Application)
  - type: web
    name: financeflow-web
    runtime: docker
    plan: starter
    region: oregon
    buildCommand: docker build -t financeflow .
    startCommand: gunicorn --bind 0.0.0.0:$PORT FinanceFlow.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: financeflow-web
          property: host
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: financeflow-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: FinanceFlow.settings
    healthCheckPath: /
    autoDeploy: true

  # PostgreSQL Database
  - type: pserv
    name: financeflow-db
    runtime: postgresql
    plan: starter
    region: oregon
    databaseName: financeflow_db
    databaseUser: financeflow_user
    envVars:
      - key: DB_NAME
        value: smartnotify
      - key: DB_USER
        value: smartnotify_user
      - key: DB_PASSWORD
        value: 7eh2YmGGeJUM1rhIhJsdDNPQLzOhlsYG


# Environment Groups (for shared environment variables)
envVarGroups:
  - name: django-config
    envVars:
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DJANGO_SETTINGS_MODULE
        value: FinanceFlow.settings
      - key: PORT
        value: 8000